# Generated by Django 3.2.5 on 2022-01-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=256)),
                ('company_name', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('invoice_date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('invoice_no', models.CharField(default=-1, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.user')),
            ],
        ),
    ]
