# Generated by Django 3.2.5 on 2022-01-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invoicedOver1000',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
