# Generated by Django 3.2.5 on 2022-01-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_user_invoicedover1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_first_name', models.CharField(max_length=64)),
                ('cs_last_name', models.CharField(max_length=64)),
                ('cs_email', models.EmailField(max_length=256)),
                ('cs_country', models.CharField(max_length=256)),
                ('cs_company', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CRM.user')),
            ],
        ),
    ]
