# Generated by Django 3.2.5 on 2022-01-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cs_open_payment',
            field=models.BooleanField(default=False),
        ),
    ]
