# Generated by Django 3.2.5 on 2022-01-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_external_id',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
