# Generated by Django 3.2.5 on 2022-01-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_auto_20220124_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cl_external_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
